#' Detect texts marked by keywords in the doc and replace them with dynamic text & numbers.
#'
#' This function takes a docx template file (e.g. TLR shell with keywords like "TTsubjectTT"), and replace them with texts dynamically generated by user's R code.
#'
#' @param doc_object Can be either a string or officer object. If string, a path to the folder where your doc or docx is saved. If officer object, should be the doc/docx loaded by officer::read_docx()
#' @param keyword Keyword in the document to be replaced.
#' @param replacement The text that you want to insert at the keyword position.
#' @param return_to_file Optional path to save the modified document. If NULL, returns officer object.
#' @returns officer object or writing to files instead
#' @examples
#' # You can provide docx object
#' docx_path <- system.file("extdata", "Keywords_replace.docx", package = "RapTLR")
#' 
#' newdocx <- textReplace(doc_object = docx_path,
#'                        keyword = "TTsubjectTT",
#'                        replacement = "This is new text")
#' 
#' # You can also provide docx object in the environment 
#' docx_path <- system.file("extdata", "Keywords_replace.docx", package = "RapTLR")
#' docx_imported <- officer::read_docx(docx_path)
#' 
#' newdocx <- textReplace(doc_object = docx_imported,
#'                        keyword = "TTsubjectTT",
#'                        replacement = "This is new text")
#' 
#' # You can provide the name of the new document
#' docx_imported <- officer::read_docx(docx_path)
#' textReplace(doc_object = docx_imported,
#'             keyword = "TTsubjectTT",
#'             replacement = "This is new text",
#'             return_to_file = file.path( getwd(), "new_docx.docx" ))
#' 
#' # You can use R's built-in or dplyr's function chains to chain your functions
#' docx_imported <- officer::read_docx(docx_path)
#' textReplace(doc_object = docx_imported,
#'             keyword = "TTsubjectTT",
#'             replacement = "This is new text")  |>
#' textReplace(keyword = "TTsiteTT", 
#'             replacement = "This is new text 2") |>
#' textReplace(keyword = "TTconclusionTT", 
#'             replacement = "This is new text 3", 
#'             return_to_file = "TLR_shell_replaced_texts.docx")
#'
#' # See help(run_apdx) or Github landing page for additional details..
#' @importFrom crosstable body_add_normal
#' @export


textReplace <- function(doc_object,
                        keyword,
                        replacement,
                        return_to_file = NULL) {
  
  if (is.null(doc_object) || is.null(keyword) || is.null(replacement)) {
    stop("doc_object, keyword, and replacement must be specified. Please see function help for details, help(textReplace).")
  }

  if (is.character(doc_object)) {
    if (file.exists(doc_object)) {
      doc_object <- officer::read_docx(doc_object)
    } else {
      stop("doc_object was specified as a path to file, and this path to file doesn't exist. Please double check your path.")
    }
  }


  ## return_to_file ----
  if (is.null(return_to_file)) {
    return_to_file <- file.path(getwd(), "TLR_updated.docx")
  } else if (!grepl("^[/~]", return_to_file)) {
    return_to_file <- file.path(getwd(), return_to_file)
  }
  
  if (!dir.exists(dirname(return_to_file)))
    stop("Error: Directory for 'return_to_file' does not exist")
  
  if (!grepl("\\.docx$", return_to_file, ignore.case = TRUE))
    return_to_file <- paste0(return_to_file, ".docx")

  
  doc_object_mod <- officer::cursor_reach(doc_object, keyword)
  doc_object_mod <- crosstable::body_add_normal(doc_object_mod, replacement)
  doc_object_mod <- officer::cursor_reach(doc_object_mod, keyword)
  doc_object_mod <- officer::body_remove(doc_object_mod)
  

  message(paste0("Writing to: ", return_to_file))
  print(doc_object_mod, return_to_file)
  invisible(doc_object)
}
