#' Detect texts marked by keywords in the doc and replace them with dynamic text & numbers.
#'
#' This function takes a docx template file (e.g. TLR shell with keywords like "TTsubjectTT"), and replace them with texts dynamically generated by user's R code.
#'
#' @param doc_ojbect Can be either a string or officer object. If string, a path to the folder where your doc or docx is saved. If officer object, should be the doc/docx loaded by officer::read_docx()
#' @param path_docx Path to the folder where your target docx is saved.
#' @param replacement The text that you want to insert at the keyword position.
#' @returns officer object or writing to files instead
#' @examples
#' # By default, not returning to file, pass the officer object to the next function one by one
#' outTLR = textReplace(
#'             doc_object = "C:/Documents/TLR/your_shell.docx",
#'             keyword = "TTsubjectTT",
#'             replacement = "This is new text"
#'             )
#' outTLR = textReplace(
#'             doc_object = outTLR,
#'             keyword = "TTsomethingTT",
#'             replacement = "Some new text"
#'             )
#' # In fact you can even use dplyr's function chains
#'
#' ...
#' # In the end, when you are done replacing texts, you can write to file
#' textReplace(
#'             doc_object = outTLR,
#'             keyword = "TTsomethingelseTT",
#'             replacement = "New texts",
#'             return_to_file = "C:/Documents/TLR/your_shell_replaced.docx"
#'             )
#'
#' # or you can write to file manually using officer
#' print( outTLR,  "C:/Documents/TLR/your_shell_replaced.docx" )
#'
#' # You can use R's built-in or dplyr's function chains to chain your functions
#' textReplace(
#'             doc_object = file.path(path_docx, "TLR_shell.docx"),
#'             keyword = "TTsubjectTT",
#'             replacement = "This is new text")  |>
#'   textReplace(keyword = "TTsomethingTT", replacement = "This is new text 2") |>
#'   textReplace(keyword = "TTsomething2TT", replacement = "This is new text 3") |>
#'   textReplace(keyword = "TTsomethingelseTT", replacement = "This is some final new text",
#'               return_to_file = file.path(path_docx, "TLR_shell_replacedtexts.docx"))
#'
#' # See help(run_apdx) or Github landing page for additional details..
#' @export


textReplace <- function(doc_object = NULL,
                        keyword = "TTsomethingTT",
                        replacement = NULL,
                        return_to_file = NULL) {
  library(officer)
  if (is.null(doc_object) || is.null(replacement)) {
    stop("path_TLFs, docx_object, and keyword must be specified. Please see function help for details, help(run_apdx).")
  }

  if (is.character(doc_object)) {
    if (file.exists(doc_object)) {
      doc_object <- officer::read_docx(doc_object)
    } else {
      stop("doc_object was specified as a path to file, and this path to file doesn't exist. Please double check your path.")
    }
  }

  # replacement<-sprintf("This double-blind, placebo-controlled, multicenter study randomized %i children and adolescents in the United States with a DSM-IV diagnosis of bipolar I disorder. The majority of subjects were white (%.0f%%) and 51%% of the subjects were female. The mean age was 13 years, ranging from 10 to 17 years (\\@ref(Appendix_1)).",
  #              169, 20)

  outTLR0 <- doc_object
  outTLR0 <- cursor_reach(outTLR0, keyword)
  outTLR0 <- body_add_par(outTLR0, replacement)
  outTLR0 <- cursor_reach(outTLR0, keyword)
  outTLR0 <- body_remove(outTLR0)   #,"TTsubjectTT")

  if (is.null(return_to_file)) {
    return(outTLR0)
  } else if (is.character(return_to_file) && !return_to_file == "") {
    message(paste0("Message: return_to_file was specified. Writing the docx to file: ", return_to_file))
    print(outTLR0,  return_to_file)
  } else {
    stop("return_to_file must be either left as NULL or specified as a valid file path.")
  }

}
